MVCLinqTutorial/Models/ContextoLINQTutorial.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLinqTutorial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextoLINQTutorial : DbContext
    {
        public ContextoLINQTutorial()
            : base("name=ContextoLINQTutorial")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<USUARIOS> USUARIOS { get; set; }
    }
}

MVCLinqTutorial/Models/ContextoLINQTutorial.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\Miguel\source\repos\MVCLinqTutorial\MVCLinqTutorial\Models\ContextoLINQTutorial.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

MVCLinqTutorial/Models/ContextoLINQTutorial.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

MVCLinqTutorial/Models/ModeloUsuarios.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCLinqTutorial.Models
{
    public class ModeloUsuarios
    {
        //CREAMOS LA VARIABLE ContextoLINQTutorial
        ContextoLINQTutorial contexto;

        public ModeloUsuarios()
        {
            //INICIALIZAMOS LA VARIABLE COMO OBJETO
            contexto = new ContextoLINQTutorial();
        }

        //MÉTODO PARA RECOGER LOS USUARIOS
        public List<USUARIOS> GetUsuarios()
        {
            //ALMACENAMOS LOS DATOS RECOGIDOS MEDIANTE LA CONSULTA EN LA VARIABLE listausu
            var listausu = (from datos in contexto.USUARIOS
                           select datos).ToList();

            //DEVOLVEMOS LOS DATOS DE LA CONSULTA PARA POSTERIORMENTE SER USADA EN UsuariosController
            return listausu;
        }

        //MÉTODO PARA INSERTAR USUARIOS
        public void InsertarUsuario(String nombre, String apellido)
        {
            //CREAMOS EL OBJETO usuario
            USUARIOS usuario = new USUARIOS();

            //DAMOS VALORES A SUS COLUMNAS
            usuario.ID = (from datos in contexto.USUARIOS
                          select datos.ID).Max() + 1;
            usuario.NOMBRE = nombre;
            usuario.APELLIDO = apellido;

            //AÑADIMOS EL USUARIO AL CONTEXTO
            contexto.USUARIOS.Add(usuario);

            //GUARDAMOS LOS CAMBIOS
            contexto.SaveChanges();
        }

        //MÉTODO PARA ELIMINAR USUARIOS
        public void EliminarUsuario(int id)
        {
            //BUSCAMOS EL USUARIO QUE QUEREMOS BORRAR
            var usuario = (from datos in contexto.USUARIOS
                           where datos.ID == id
                           select datos).FirstOrDefault();

            //ELIMINAMOS AL USAURIO DEL CONTEXTO
            contexto.USUARIOS.Remove(usuario);

            //GUARDAMOS LOS CAMBIOS
            contexto.SaveChanges();
        }

        //MÉTODO PARA EDITAR USUARIOS
        public void EditarUsuario(int id, String nombre, String apellido)
        {
            //BUSCAMOS EL USUARIO QUE QUEREMOS EDITAR
            USUARIOS usuario = this.DetallesUsuario(id);

            //ACTUALIZAMOS LOS DATOS ACTUALES POR LOS PARÁMETROS RECIBIDOS
            usuario.NOMBRE = nombre;
            usuario.APELLIDO = apellido;

            //GUARDAMOS LOS CAMBIOS
            contexto.SaveChanges();
        }

        //MÉTODO PARA VER DETALLES DE USUARIOS
        public USUARIOS DetallesUsuario(int id)
        {
            //BUSCAMOS EL USUARIO DEL QUE QUEREMOS VER LOS DETALLES
            var usuario = (from datos in contexto.USUARIOS
                           where datos.ID == id
                           select datos).FirstOrDefault();

            //DEVOLVEMOS EL USUARIO
            return usuario;

            //return contexto.USUARIOS.Find(id);
        }
    }
}

MVCLinqTutorial/Models/USUARIOS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLinqTutorial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
    }
}

MVCLinqTutorial/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLinqTutorial.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCLinqTutorial/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//IMPORTAMOS LA CARPETA Models
using MVCLinqTutorial.Models;

namespace MVCLinqTutorial.Controllers
{
    public class UsuariosController : Controller
    {
        //CREAMOS LA VARIABLE ModeloUsuarios
        ModeloUsuarios modelo;

        public UsuariosController()
        {
            //INICIALIZAMOS LA VARIABLE COMO OBJETO
            modelo = new ModeloUsuarios();
        }

        // GET: Lista
        public ActionResult Lista()
        {
            //LLAMAMOS AL MÉTODO GetUsuarios() Y LO ALMACENAMOS EN LA VARIABLE listausu
            List<USUARIOS> listausu = modelo.GetUsuarios();

            return View(listausu);
        }

        //GET: Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: Create
        [HttpPost]
        public ActionResult Create(String NOMBRE, String APELLIDO)
        {
            modelo.InsertarUsuario(NOMBRE, APELLIDO);

            return RedirectToAction("Lista");
        }

        //GET: Delete
        public ActionResult Delete(int ID)
        {
            modelo.EliminarUsuario(ID);

            return RedirectToAction("Lista");
        }

        //GET: Edit
        public ActionResult Edit(int ID)
        {
            USUARIOS usuario = modelo.DetallesUsuario(ID);

            return View(usuario);
        }

        //POST: Edit
        [HttpPost]
        public ActionResult Edit(int ID, String NOMBRE, String APELLIDO)
        {
            modelo.EditarUsuario(ID, NOMBRE, APELLIDO);

            return RedirectToAction("Lista");
        }

        //GET: Details
        public ActionResult Details(int ID)
        {
            USUARIOS usuario = modelo.DetallesUsuario(ID);

            return View(usuario);
        }
    }
}

MVCLinqTutorial/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCLinqTutorial/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCLinqTutorial/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCLinqTutorial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LINQ Tutorial", "Lista", "Usuarios", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Lista usuarios", "Lista", "Usuarios")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCLinqTutorial/Views/Usuarios/Create.cshtml
@model MVCLinqTutorial.Models.USUARIOS

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USUARIOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.APELLIDO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCLinqTutorial/Views/Usuarios/Details.cshtml
@model MVCLinqTutorial.Models.USUARIOS

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>USUARIOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.APELLIDO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APELLIDO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCLinqTutorial/Views/Usuarios/Edit.cshtml
@model MVCLinqTutorial.Models.USUARIOS

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USUARIOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.APELLIDO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCLinqTutorial/Views/Usuarios/Lista.cshtml
@model IEnumerable<MVCLinqTutorial.Models.USUARIOS>

@{
    ViewBag.Title = "Lista";
}

<h2>Lista</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover" border="3">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NOMBRE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.APELLIDO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NOMBRE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.APELLIDO)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>